##################################################################
##                    Date and time patterns                    ##
##################################################################

pattern.date.full = yyyy-MM-dd HH:mm:ss
pattern.date = yyyy-MM-dd
pattern.time = HH:mm:ss
pattern.date.time = yyyy-MM-dd HH:mm

# classname + key = localized message
hu.evocelot.auth.dto.exception.enums.FaultType.SAMPLE_INVALID_RESPONSE = Sample hu
hu.evocelot.auth.dto.exception.enums.FaultType.REST_BAD_REQUEST = A kérésben szereplő tartalom rosszul formázott!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_UNAUTHORIZED = Hibás hitelesítési adatok!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_FORBIDDEN = A felhasználónak nincs joga a művelet végrehajtására!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_NOT_FOUND = Nem létező végpont!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_METHOD_NOT_ALLOWED = A végpont nem támogatja a küldött HTTP metódust!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_NOT_ACCEPTABLE = A végpont nem támogatja a várt (accept) MIME típust!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_UNSUPPORTED_MEDIA_TYPE = A végpont nem támogatja a küldött (content-type) MIME típust!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_INTERNAL_SERVER_ERROR = Hiba történt a művelet végrehajtásában, kérjük próbálja újra később!
hu.evocelot.auth.dto.exception.enums.FaultType.REST_SERVICE_UNAVAILABLE = A szolgáltatás jelenleg nem fogad el kéréseket!
hu.evocelot.auth.dto.exception.enums.FaultType.SAMPLE_NOT_FOUND = A minta entitás nem található!
hu.evocelot.auth.dto.exception.enums.FaultType.EMAIL_ALREADY_IN_USE = Az email cím már használatban van!
hu.evocelot.auth.dto.exception.enums.FaultType.PERMISSION_NAME_ALREADY_IN_USE = A jogosultság neve már használatban van!
hu.evocelot.auth.dto.exception.enums.FaultType.SECURITY_GROUP_NAME_ALREADY_IN_USE = A jogosultsági csoport neve már használatban van!
hu.evocelot.auth.dto.exception.enums.FaultType.SECURITY_GROUP_IS_UNDER_USE = A jogosultsági csoport használatban van!
hu.evocelot.auth.dto.exception.enums.FaultType.QUERY_FAILED = A listázás nem sikerült!
